services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_manim_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_worker
    restart: unless-stopped
    env_file:
      - .env
    command: celery -A app.core.queue.taskQueue worker --loglevel=info --concurrency=1
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_manim_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend


