name: build and Deploye
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            
            - name: Docker login
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Build and push frontend image
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/ai-manim-video-generator-frontend:${{ github.sha }}
                  ${{ secrets.DOCKERHUB_USERNAME }}/ai-manim-video-generator-frontend:latest

            - name: Build and push backend image
              uses: docker/build-push-action@v5
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: |
                    ${{secrets.DOCKERHUB_USERNAME}}/ai-manim-video-generator-backend:${{github.sha}}
                    ${{ secrets.DOCKERHUB_USERNAME }}/ai-manim-video-generator-backend:latest